server:
  host: "127.0.0.1"
  port: 8080

google_photos:
  client_secret_path: "client_secret.json"
  scopes:
    - "https://www.googleapis.com/auth/photoslibrary.readonly"
    - "openid"
    - "https://www.googleapis.com/auth/userinfo.email"
  redirect_port: 1008
  albums:
    - "Twitter"
  token_store: "data/google_photos_token.json"
  album_url: ""
  oauth_client:
    web:
      client_id: "644950207841-o8bgtioef7105v3ood2mdrfomfahdspj.apps.googleusercontent.com"
      auth_uri: "https://accounts.google.com/o/oauth2/auth"
      token_uri: "https://oauth2.googleapis.com/token"
      redirect_uris:
        - "http://localhost:1008/"

llm:
  oracle_model: "gemini-1.5-flash-latest"
  embedding_model: "text-embedding-004"
  api_key_env: "GOOGLE_API_KEY"

db:
  service_account_key_path: "gcloud-service-account.json"
  dimension: 768

storage:
  images_dir: "data/images"
  thumbs_dir: "data/thumbs"
  max_download_size: "w2048-h2048"
